name: json_schema
version: 2.2.1
description: Provide support for validating instances against json schema
authors:
  - Michael Carter <michael.carter@workiva.com>
  - Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/workiva/json_schema

environment:
  sdk: ">=1.24.3 <3.0.0"

dependencies:
  args: ">=0.13.7 <2.0.0"
  collection: ^1.14.6
  dart2_constant: ^1.0.0
  logging: ">=0.9.3 <0.12.0"
  path: ^1.3.0
  uri: ">=0.11.1 <0.12.0"
  w_transport: ^3.2.8

dev_dependencies:
  build_runner: ">=0.6.0 <2.0.0"
  build_test: ^0.10.9
  build_web_compilers: ^2.9.0
  coverage: ^0.13.9
  dart_dev: ^3.6.1
  dart_style: ^1.3.6
  dependency_validator: ^1.3.0
  glob: ^1.2.0
  shelf: ^0.7.2
  shelf_static: ^0.2.7
  test: ^1.15.7
  test_html_builder: ^1.0.2
